FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential libpq-dev pkg-config \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Set a dummy DATABASE_URL so collectstatic doesn't try to load MySQL
ENV DATABASE_URL=sqlite:///tmp/db.sqlite3

RUN python manage.py collectstatic --no-input

EXPOSE 8000

CMD ["sh", "-c", "python manage.py migrate && python manage.py  && python manage.py seed_data seed_data && gunicorn hrms.wsgi:application --bind 0.0.0.0:${PORT:-8000}"]
